services:
  - type: web
    name: agrogpt-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn agrogpt_web.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 